#!/bin/sh

# Report pypevue and geodome links in local python lib or bin
# directories; that is, in .local's site-packages directory or its bin
# directory.  Also see: new-bin-lib-links

LLIB=$(python3 -c "import sys; print ([x for x in sys.path if '/home/' in x][0])")
LBIN=$HOME/.local/bin
date
echo; echo "Program Links in $LBIN:"
ls --color -l   $LBIN/pypevu*   $LBIN/geo*dome

echo; echo "Module Links in $LLIB:"
ls --color -dl  $LLIB/pypevue  $LLIB/geo*dome
echo
