#!/bin/sh

# yume-setImportLinks makes a menu with choices to set links from
# directories for modules pypevue and pypevu

MAINMOD=pypevue
PROGMOD=pypevu
SITEDIR=$HOME/.local/lib/python3.6/site-packages
export MAINMOD PROGMOD SITEDIR

yume -at 480x235-4+1266\
 -bu -ex  -la 'Edit menu' "x2 $0"  -la 'Reload menu' "%+$0"\
 -bu -la 'echo; ln -fs $MDIR $SITEDIR/$MAINMOD; ls -l $SITEDIR/$MAINMOD' -la "Make site-packages link for $MAINMOD equal to:" -la MDIR -iv "$PWD" \
 -bu "echo;ls -l $SITEDIR/pype*; echo"\
 -bu -la 'echo; ln -fs $PNAM $SITEDIR/$PROGMOD; ls -l $SITEDIR/$PROGMOD*' -la "Make site-packages link for $PROGMOD equal to:" -la PNAM -iv "$PWD/$PROGMOD.py"\
 