#!/bin/sh

# Script to make "Golden Master" files for automatic-test comparisons
# - jiw - 17 July 2020
echo $0 - 'Makes a gm-eg-* file for each eg-* file in examples/'

pvDir=../src/pypevue
egDir=$pvDir/examples

for fp in $egDir/eg-* ; do
    f=${fp##.*/}
    echo Making gm-$f for $fp
    $pvDir/pypevu.py f=$fp
    mv pypevu.scad gm-$f
done

# Drop data for tests we don't want to run
rm  -f  gm-eg-t  gm-eg-geo-6a  gm-eg-freq-6-woven-hemi
ls -l gm*
date
